# Generated by Django 4.0.6 on 2023-09-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0003_orderacceptnotifcation_orderaccept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaccept',
            old_name='order_placed',
            new_name='order_accept',
        ),
    ]
