# Generated by Django 4.0.6 on 2023-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0004_rename_order_placed_orderaccept_order_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderacceptnotifcation',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
