# Generated by Django 4.0.6 on 2023-09-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0005_alter_orderacceptnotifcation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderacceptnotifcation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderacceptnotifcation',
            name='mom',
        ),
        migrations.DeleteModel(
            name='OrderAccept',
        ),
        migrations.DeleteModel(
            name='OrderAcceptNotifcation',
        ),
    ]
