# Generated by Django 4.0.6 on 2023-09-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0007_orderaccept_orderacceptnotifcation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifcation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='notifcation',
            name='mom',
        ),
        migrations.DeleteModel(
            name='OrderAccept',
        ),
        migrations.RemoveField(
            model_name='orderacceptnotifcation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderacceptnotifcation',
            name='mom',
        ),
        migrations.RemoveField(
            model_name='orderacceptnotifcation',
            name='ordered_item',
        ),
        migrations.DeleteModel(
            name='Notifcation',
        ),
        migrations.DeleteModel(
            name='OrderAcceptNotifcation',
        ),
    ]
