# Generated by Django 4.0.6 on 2023-09-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0009_orderacceptnotifcation_orderaccept_notifcation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAccept',
        ),
    ]
