# Generated by Django 4.0.6 on 2023-09-26 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0010_delete_orderaccept'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('order_placed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_accept', to='mom.orderplaced')),
            ],
        ),
    ]
