# Generated by Django 4.0.6 on 2023-09-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0011_orderaccept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAcceptNotifcation',
        ),
    ]
