# Generated by Django 4.0.6 on 2023-09-26 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('mom', '0012_delete_orderacceptnotifcation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAcceptNotifcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_order_accept', to='customer.customer')),
                ('mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_order_accept', to='mom.mommodel')),
                ('order_accept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mom.orderaccept')),
                ('ordered_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_accept', to='mom.orderitem')),
            ],
        ),
    ]
