# Generated by Django 4.0.6 on 2023-09-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0014_alter_orderacceptnotifcation_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
