# Generated by Django 4.0.6 on 2023-09-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0016_payment_recipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipt',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Recipt',
        ),
    ]
