# Generated by Django 4.0.6 on 2023-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0018_payment_recipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipt',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
